# Generated by Django 4.0 on 2023-10-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otpvarify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='varify',
            new_name='verify',
        ),
    ]
